version: "3.8"
services:
  api:
    container_name: api
    depends_on:
      - mysql
    restart: always
    build: 
      context: ./
      dockerfile: docker/nodejs/Dockerfile
    ports:
      - 80:3000
    volumes:
    - ./index.js:/app/index.js
    - ./src:/app/src
    - ./.env:/app/.env
    - ./node_modules:/app/node_modules
    - ./package.json:/app/package.json
    - ./package-lock.json:/app/package-lock.json
    command: npm run dev
  mysql:
    image: mysql:8.0.29-debian
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin:5.1.3-apache
    container_name: phpmyadmin
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    volumes:
      - ./docker/phpMyadmin/apache2.conf:/etc/apache2/apache2.conf
